### ISSUE TITLE
why we use it , 

### ISSUE THREAD

**Issue by azabcodes** [SilentCatD/bloc_notification#1]

**Comment by SilentCatD** [comment]
Hey @mazab99 

In short, this package provides a solution for separating UI-related actions such as `showDialog` and `navigation` from the state in order to simplify their handling. 

For instance, suppose your state class has a `message` variable containing a message to show in a dialog. However, if you use `Equatable`, emitting the same message repeatedly won't trigger the dialog. This can be solved by setting the `message` variable to null when the dialog is completed or avoiding the use of `Equatable`, but to do this repeatedly is rather burdensome. 
Or you can create multiple state sub-classes, but doing so would hinder the use of `copyWith` methods. `copyWith` is commonly used to copy existing state and modify certain properties, which is a powerful and convenient feature.

This package offers a proposal to solve these types of problems and is compatible with both Bloc and Cubit. The idea is quite simple too, adding another stream in `BlocBase`, and an additional callback in `Widget`
